datagrid:
    issues-grid:
        source:
            acl_resource: testtaskoro.issue_view
            type: orm
            query:
                select:
                    - v.id
                    - v.summary
                    - v.code
                    - v.createdAt

                from:
                    - { table: MagecoreTestTaskOroBundle:Issue, alias: v }
        columns:
            summary:
                label: Model
            code:
                label: '# Seats'
            createdAt:
                label: Bought at
                frontend_type: date
        properties:
            id: ~
            update_link:
                type: url
                route: magecore_testtaskoro.issue_update
                params:
                    - id
            view_link:
                type: url
                route: magecore_testtastoro.issue_view
                params:
                    - id
            delete_link:
                type: url
                route: magecore_testtaskoro_api_delete_issue
                params:
                    - id
        sorters:
            columns:
                summary:
                    data_name: v.summary
                code:
                    data_name: v.code
                createdAt:
                    data_name: v.createdAt
            default:
                createAt: ASC
        filters:
            columns:
                summary:
                    type: string
                    data_name: v.summary
                code:
                    type: number
                    data_name: v.code
                createdAt:
                    type: date
                    data_name: v.createdAt
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  testtaskoro.issue_view
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  magecore_testtaskoro.issue_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  magecore_testtaskoro.issue_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link