datagrid:
    issues-grid:
        source:
            acl_resource: testtaskoro.issue_view
            type: orm
            query:
                select:
                    - v.id
                    - v.summary
                    - v.type
                    - v.code
                    - issuePriority.label as priorityLabel
                    - issueResolution.value as resolutionLabel
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                    - CONCAT(assignedTo.firstName, CONCAT(' ', assignedTo.lastName)) as assigneeName
                    - assignedTo.id as assignedToId
                    - v.createdAt
                    - v.updatedAt

                from:
                    - { table: MagecoreTestTaskOroBundle:Issue, alias: v }
                join:
                    left:
                        - { join: v.priority, alias: issuePriority }
                        - { join: v.resolution, alias: issueResolution }
                        - { join: v.assignedTo, alias: assignedTo }
                        - { join: v.reporter, alias: owner }
        columns:
            code:
                label: '# code'
            summary:
                label: Summary
            type:
                label: Type
            priorityLabel:
                label: priority
            resolutionLabel:
                label: resolution
            ownerName:
                type:          twig
                label:         reporter
                frontend_type: html
                template:      MagecoreTestTaskOroBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                type:          twig
                label:         assignee
                frontend_type: html
                template:      MagecoreTestTaskOroBundle:Issue:Datagrid/Property/assignedTo.html.twig
            createdAt:
                label: created
                frontend_type: datetime
            updatedAt:
                label: updated
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: magecore_testtaskoro.issue_update
                params:
                    - id
            view_link:
                type: url
                route: magecore_testtastoro.issue_view
                params:
                    - id
            delete_link:
                type: url
                route: magecore_testtaskoro_api_delete_issue
                params:
                    - id
        sorters:
            columns:
                summary:
                    data_name: v.summary
                code:
                    data_name: v.code
                priorityLabel:
                    data_name: issuePriority.order
                createdAt:
                    data_name: v.createdAt
                updatedAt:
                    data_name: v.updatedAt
            default:
                updatedAt: ASC
        filters:
            columns:
                summary:
                    type: string
                    data_name: v.summary
                code:
                    type: string
                    data_name: v.code
                createdAt:
                    type: date
                    data_name: v.createdAt
                priorityLabel:
                    type:      string
                    data_name: priorityLabel
                ownerName:
                    type:      string
                    data_name: ownerName
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  testtaskoro.issue_view
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  magecore_testtaskoro.issue_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  magecore_testtaskoro.issue_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
    issue-subtask-grid:
        source:
            acl_resource: testtaskoro.issue_view
            type: orm
            query:
                select:
                    - v.id
                    - v.summary
                    - v.type
                    - v.code
                from:
                    - { table: MagecoreTestTaskOroBundle:Issue, alias: v }
                where:
                    and:
                        - v.parentIssue = :parentId
        columns:
            code:
                label: '# code'
                type:          twig
                frontend_type: html
                template:      MagecoreTestTaskOroBundle:Issue:Datagrid/Property/subtask.html.twig
            summary:
                label: Summary
    issue-assigned-grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - (assignedTo.id = :id OR owner.id = :id)
            bind_parameters:
                - id
        options:
            entity_pagination: false
