parameters:
    magecore_testtaskoro.form.type.task.class:               Magecore\Bundle\TestTaskOroBundle\Form\Type\IssueType


services:
    magecore_testtaskoro.form.type.issue:
        class: %magecore_testtaskoro.form.type.task.class%
        tags:
            - { name: form.type, alias: magecore_testtaskoro_issue }

    orocrm_task.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'magecore_testtaskoro'
            - 'magecore_testtaskoro'