parameters:
    magecore_testtaskoro.form.type.issue.class:               Magecore\Bundle\TestTaskOroBundle\Form\Type\IssueType
    magecore_testtaskoro.form.type.issue.api.class:           Magecore\Bundle\TestTaskOroBundle\Form\Type\IssueApiType


services:
    magecore_testtaskoro.form.type.issue:
        class: %magecore_testtaskoro.form.type.issue.class%
        tags:
            - { name: form.type, alias: magecore_testtaskoro_issue }

    orocrm_task.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'magecore_testtaskoro'
            - 'magecore_testtaskoro'

    magecore_testtaskoro.form.type.issue.api:
        class:                                      %magecore_testtaskoro.form.type.issue.api.class%
        arguments:
            - @router
            - @oro_locale.formatter.name
            - @oro_security.security_facade
        tags:
            - { name: form.type, alias: account }