placeholders:
    view_content_data_additional_information:
        items:
            magecore_testtaskoro_issue_grid: ~

items:
    magecore_testtaskoro_issue_grid:
        template: MagecoreTestTaskOroBundle:Issue:user.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
