Magecore\Bundle\TestTaskOroBundle\Entity\Issue:
    alias:                          magecore_testtaskoro_issue
    label:                          Demo products
    title_fields:                   [summary]
    route:
        name:                       magecore_testtastoro.issue_view
        parameters:
            id:                     id
    search_template:                MagecoreTestTaskOroBundle:Search:result.html.twig
    fields:
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
        -
            name:                   code
            target_type:            text
            target_fields:          [code]
        -
            name:                   type
            target_type:            text
            target_fields:          [type]
        -
            name:                   priority
            target_type:            text
            target_fields:          [priority]
        -
            name:                   resolution
            target_type:            text
            target_fields:          [resolution]
        -
            name:                   reporter
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           username
                    target_type:    text
                    target_fields:  [username]
                -
                    name: firstName
                    target_type: text
                    target_fields: [firstName]
                -
                    name: lastName
                    target_type: text
                    target_fields: [lastName]
        -
            name:                   assignedTo
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           username
                    target_type:    text
                    target_fields:  [username]
                -
                    name: firstName
                    target_type: text
                    target_fields: [firstName]
                -
                    name: lastName
                    target_type: text
                    target_fields: [lastName]

