Magecore\Bundle\TestTaskOroBundle\Entity\Issue:
    alias:                          magecore_testtaskoro_issue
    label:                          Demo products
    title_fields:                   [summary]
    route:
        name:                       magecore_testtastoro.issue_view
        parameters:
            id:                     id
    search_template:                MagecoreTestTaskOroBundle:Search:result.html.twig
    fields:
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
        -
            name:                   description
            target_type:            text
            target_fields:          [description]
        -
            name:                   type
            target_type:            text
            target_fields:          [type]
        -
            name:                   priority
            target_type:            text
            target_fields:          [priority]
        -
            name:                   resolution
            target_type:            text
            target_fields:          [resolution]
        -
            name:                   reporter
            target_type:            text
            target_fields:          [reporter]
        -
            name:                   assignedTo
            target_type:            text
            target_fields:          [assignedTo]
