Magecore\Bundle\TestTaskOroBundle\Entity\Issue:
    alias:                          orocrm_task
    label:                          Demo products
    title_fields:                   [summary]
    route:
        name:                       magecore_testtastoro.issue_view
        parameters:
            id:                     id
    search_template:                OroCRMTaskBundle:Search:result.html.twig
    fields:
        -
            name:                   summary
            target_type:            text
            target_fields:          [summary]
        -
            name:                   description
            target_type:            text
            target_fields:          [description]
