Magecore\Bundle\TestTaskOroBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        reporter:
            - NotBlank: ~
        priority:
            - NotBlank: ~
        type:
            - NotBlank: ~
