magecore_testtaskoro:
    resource: "@MagecoreTestTaskOroBundle/Controller"
    type: annotation
    prefix: /
magecore_testtaskoro_api_issue:
    resource:     "@MagecoreTestTaskOroBundle/Controller/Api/Rest/IssueController.php"
    type:         rest
    prefix:       api/rest/{version}/
    requirements:
        version:  latest|v1
        _format:  json
    defaults:
        version:  latest